//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.SpatialLite.Core.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IOTestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IOTestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tests.SpatialLite.Core.Data.IOTestData", typeof(IOTestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] collection_2D {
            get {
                object obj = ResourceManager.GetObject("collection_2D", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] collection_2DM {
            get {
                object obj = ResourceManager.GetObject("collection_2DM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] collection_3D {
            get {
                object obj = ResourceManager.GetObject("collection_3D", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] collection_3DM {
            get {
                object obj = ResourceManager.GetObject("collection_3DM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] collection_empty {
            get {
                object obj = ResourceManager.GetObject("collection_empty", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] collection_multi {
            get {
                object obj = ResourceManager.GetObject("collection_multi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] collection_nested {
            get {
                object obj = ResourceManager.GetObject("collection_nested", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] collection_pt_ls_poly {
            get {
                object obj = ResourceManager.GetObject("collection_pt_ls_poly", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] linestring_2D {
            get {
                object obj = ResourceManager.GetObject("linestring_2D", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] linestring_2DM {
            get {
                object obj = ResourceManager.GetObject("linestring_2DM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] linestring_3D {
            get {
                object obj = ResourceManager.GetObject("linestring_3D", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] linestring_3DM {
            get {
                object obj = ResourceManager.GetObject("linestring_3DM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] linestring_empty {
            get {
                object obj = ResourceManager.GetObject("linestring_empty", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] multilinestring_2D {
            get {
                object obj = ResourceManager.GetObject("multilinestring_2D", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] multilinestring_2DM {
            get {
                object obj = ResourceManager.GetObject("multilinestring_2DM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] multilinestring_3D {
            get {
                object obj = ResourceManager.GetObject("multilinestring_3D", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] multilinestring_3DM {
            get {
                object obj = ResourceManager.GetObject("multilinestring_3DM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] multilinestring_empty {
            get {
                object obj = ResourceManager.GetObject("multilinestring_empty", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] multipoint_2D {
            get {
                object obj = ResourceManager.GetObject("multipoint_2D", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] multipoint_2DM {
            get {
                object obj = ResourceManager.GetObject("multipoint_2DM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] multipoint_3D {
            get {
                object obj = ResourceManager.GetObject("multipoint_3D", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] multipoint_3DM {
            get {
                object obj = ResourceManager.GetObject("multipoint_3DM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] multipoint_empty {
            get {
                object obj = ResourceManager.GetObject("multipoint_empty", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] multipolygon_2D {
            get {
                object obj = ResourceManager.GetObject("multipolygon_2D", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] multipolygon_2DM {
            get {
                object obj = ResourceManager.GetObject("multipolygon_2DM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] multipolygon_3D {
            get {
                object obj = ResourceManager.GetObject("multipolygon_3D", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] multipolygon_3DM {
            get {
                object obj = ResourceManager.GetObject("multipolygon_3DM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] multipolygon_empty {
            get {
                object obj = ResourceManager.GetObject("multipolygon_empty", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] point_2D {
            get {
                object obj = ResourceManager.GetObject("point_2D", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] point_2DM {
            get {
                object obj = ResourceManager.GetObject("point_2DM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] point_3D {
            get {
                object obj = ResourceManager.GetObject("point_3D", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] point_3DM {
            get {
                object obj = ResourceManager.GetObject("point_3DM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] polygon_3DM {
            get {
                object obj = ResourceManager.GetObject("polygon_3DM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] polygon_empty {
            get {
                object obj = ResourceManager.GetObject("polygon_empty", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] polygon_ext_2D {
            get {
                object obj = ResourceManager.GetObject("polygon_ext_2D", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] polygon_ext_2DM {
            get {
                object obj = ResourceManager.GetObject("polygon_ext_2DM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] polygon_ext_3D {
            get {
                object obj = ResourceManager.GetObject("polygon_ext_3D", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] polygon_ext_3DM {
            get {
                object obj = ResourceManager.GetObject("polygon_ext_3DM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] two_points_3DM {
            get {
                object obj = ResourceManager.GetObject("two_points_3DM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] wkt_geometry_collection_3DM {
            get {
                object obj = ResourceManager.GetObject("wkt_geometry_collection_3DM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] wkt_linestring_3DM {
            get {
                object obj = ResourceManager.GetObject("wkt_linestring_3DM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] wkt_multilinestring_3DM {
            get {
                object obj = ResourceManager.GetObject("wkt_multilinestring_3DM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] wkt_multipoint_3DM {
            get {
                object obj = ResourceManager.GetObject("wkt_multipoint_3DM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] wkt_multipolygon_3DM {
            get {
                object obj = ResourceManager.GetObject("wkt_multipolygon_3DM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] wkt_point_3DM {
            get {
                object obj = ResourceManager.GetObject("wkt_point_3DM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] wkt_point_and_linestring_3DM {
            get {
                object obj = ResourceManager.GetObject("wkt_point_and_linestring_3DM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] wkt_polygon_3DM {
            get {
                object obj = ResourceManager.GetObject("wkt_polygon_3DM", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
