//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.SpatialLite.Osm.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XmlTestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XmlTestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tests.SpatialLite.Osm.Data.XmlTestData", typeof(XmlTestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] osm_invalid_root_element {
            get {
                object obj = ResourceManager.GetObject("osm_invalid_root_element", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osm_node_all_properties {
            get {
                object obj = ResourceManager.GetObject("osm_node_all_properties", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osm_node_missing_timestamp {
            get {
                object obj = ResourceManager.GetObject("osm_node_missing_timestamp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osm_node_tag_without_key {
            get {
                object obj = ResourceManager.GetObject("osm_node_tag_without_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osm_node_tag_without_value {
            get {
                object obj = ResourceManager.GetObject("osm_node_tag_without_value", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osm_node_with_tag_and_unknown_element {
            get {
                object obj = ResourceManager.GetObject("osm_node_with_tag_and_unknown_element", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osm_node_with_tags {
            get {
                object obj = ResourceManager.GetObject("osm_node_with_tags", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osm_node_without_id {
            get {
                object obj = ResourceManager.GetObject("osm_node_without_id", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osm_node_without_lat {
            get {
                object obj = ResourceManager.GetObject("osm_node_without_lat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osm_node_without_lon {
            get {
                object obj = ResourceManager.GetObject("osm_node_without_lon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osm_real_file {
            get {
                object obj = ResourceManager.GetObject("osm_real_file", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osm_relation_all_properties {
            get {
                object obj = ResourceManager.GetObject("osm_relation_all_properties", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osm_relation_member_without_ref {
            get {
                object obj = ResourceManager.GetObject("osm_relation_member_without_ref", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osm_relation_member_without_type {
            get {
                object obj = ResourceManager.GetObject("osm_relation_member_without_type", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osm_relation_node {
            get {
                object obj = ResourceManager.GetObject("osm_relation_node", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osm_relation_relation {
            get {
                object obj = ResourceManager.GetObject("osm_relation_relation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osm_relation_way {
            get {
                object obj = ResourceManager.GetObject("osm_relation_way", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osm_relation_with_tags {
            get {
                object obj = ResourceManager.GetObject("osm_relation_with_tags", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osm_relation_with_tags_and_unknown_element {
            get {
                object obj = ResourceManager.GetObject("osm_relation_with_tags_and_unknown_element", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osm_relation_without_id {
            get {
                object obj = ResourceManager.GetObject("osm_relation_without_id", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osm_relation_without_members {
            get {
                object obj = ResourceManager.GetObject("osm_relation_without_members", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osm_simple_node {
            get {
                object obj = ResourceManager.GetObject("osm_simple_node", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osm_simple_way {
            get {
                object obj = ResourceManager.GetObject("osm_simple_way", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osm_small_real_file {
            get {
                object obj = ResourceManager.GetObject("osm_small_real_file", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osm_unknown_inner_element {
            get {
                object obj = ResourceManager.GetObject("osm_unknown_inner_element", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osm_way_all_properties {
            get {
                object obj = ResourceManager.GetObject("osm_way_all_properties", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osm_way_nd_without_ref {
            get {
                object obj = ResourceManager.GetObject("osm_way_nd_without_ref", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osm_way_with_tags {
            get {
                object obj = ResourceManager.GetObject("osm_way_with_tags", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osm_way_with_tags_and_unknown_element {
            get {
                object obj = ResourceManager.GetObject("osm_way_with_tags_and_unknown_element", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osm_way_without_id {
            get {
                object obj = ResourceManager.GetObject("osm_way_without_id", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osm_way_without_nodes {
            get {
                object obj = ResourceManager.GetObject("osm_way_without_nodes", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
